# Custom Language File for Launcher Customizer

[ejs.app]
title = "누텔라이브"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/nutellaive"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/nutellaive"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/nutellaive"
supportLink = "https://github.com/CustomLauncherLab/nutellaive/issues"

[ejs.welcome]
welcomeHeader = "누텔라이브를 즐겨주셔서 감사합니다."
welcomeDescription = "1인 개발인 만큼 미흡한 점도 많고 오류가 있을 수 있습니다.<br>문제가 생긴다면 누텔라를 통해 바로 문의 부탁드립니다."
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."
